### ISSUE TITLE
[Linux] Progress display bug?

### ISSUE THREAD

**Issue by pondsea** [SuperNETorg/Agama#11]
Bundle shows 99.91% 173791/173791 RT=> 173190 (Full mode on KMD). It showed that it was at 100%, i left it came back and now showing 99.91

**Comment by satindergrewal** [comment]
I'm not calculating any percentage or values for progress bar. Everything is taken just as is from iguana API output.
Please request @jl777 for any changes in there.

**Comment by satindergrewal** [comment]
I noticed the bundles and blocks are in case getting RT blocks, bundles percentage might go less or more. I think it's by design calculating things like that. All matters is the full mode in RT mode, and showing contents and working expectedly.

Please open this issue again by commenting if you still face any issue, like being in RT, and percentage change and not able to do usual wallet actions. In any case this issue still comes under iguana core API, so you must create an issue at jl777/SuperNET repo instead.
