### ISSUE TITLE
can't reinstall the desktop app

### ISSUE THREAD

**Issue by charlesrocket** [SuperNETorg/Agama#96]
after uninstalling with CleanMyMac the Agama installer still pinging software somewhere in the system. no correct install/uninstall is possible.

**Comment by satindergrewal** [comment]
The same installer which installs the app also uninstalls Agama App cleanly.

Because you did not cleanly uninstall the app, a file is still left on the system which is not letting you uninstall or install the app again.

open Terminal and remove this ini file with this command:

```
sudo rm /etc/SuperNETOrg-AgamaApp.ini
```

Once done, try installing the app again. It should work fine.

And don't remove the app manually or with other third party removers after installing. They mostly just search and find apps. Mac lacks good uninstall app features like Windows, and third-party apps mostly do a dumb job.

**Comment by charlesrocket** [comment]
thanks! had some problems downloading the chain so I thought I'll quickly reinstall it, but got myself into that box)
